### ISSUE TITLE
Chris Meyer - Git visualization tool

### ISSUE THREAD

**Issue by chris023** [turingschool-examples/memoize#3]
Interactive virtual terminals with commit, branch, push and pull methods and a visual representation of whats going on when these happen

<img width="896" alt="screen shot 2018-11-02 at 9 59 27 am" src="https://user-images.githubusercontent.com/7797319/47926419-1db22c00-de86-11e8-8c5d-6842af6324b3.png">

**Comment by brittanystoroz** [comment]
Confirmed and discussed
