### ISSUE TITLE
Jake Lauer CSS Ani-Mate

### ISSUE THREAD

**Issue by jakelauer27** [turingschool-examples/memoize#5]
I'd like to create an app to help people learn how to use CSS Animations.  
Here is a quick sketch of what the site would look like.

<img width="1050" alt="screen shot 2018-11-02 at 9 55 17 am" src="https://user-images.githubusercontent.com/41130521/47926169-88169c80-de85-11e8-9722-b85efe51698b.png">

Users would be provided with 2 squares to animate on the right side and a code editor on the left side.
The code editor would have two tabs, one for keyframes and the other for the animation property.

The editor start prefilled with the animation properties setup and a basic keyframe setup.   The user can then play around and experiment with animations.  
There is a reset button for resetting the animations, a save button for saving the animation to local storage.
There is a play button for playing the animation and a stop button for stopping the animation.
There is a load animation button for loading a previous animation or one of several examples I will have prepopulated. 
There is a ? button for providing info on how to use keyframes and the animation property.  

I plan on using the react codemirror component https://github.com/JedWatson/react-codemirror for the in-app code editor (the same one chrome uses).

**Comment by brittanystoroz** [comment]
Confirmed and discussed
