### ISSUE TITLE
Jamie - Recursion Project Idea

### ISSUE THREAD

**Issue by jarushford** [turingschool-examples/memoize#6]
Wanting to make an app with two parts, one that has a line-by-line walkthrough of a function (probably sorting algorithm) using recursion with some sort of visual representation of what is happening. Then the other part would be a code editor with a practice problem(s) that people can attempt and it will give feedback on whether it is correct (codewars-esque). I definitely have a few questions about parts of it (also just generally wondering your thoughts on the scale of how much that would be to do in a short time...) so I am curious to hear your thoughts or maybe check in quick sometime today about some parts of it.

**Comment by brittanystoroz** [comment]
Confirmed and discussed
